
version: "3.4"
services:
  http_server:
    env_file:
      - .env
    expose:
      - "80"
    image: '${REGISTRY_NAME}henkel/bittorrent-tracker:latest'
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    networks:
      - "reverseproxy"
      - "internal"
networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal:
