
version: "3.4"
services:
  http_server:
    build: ./dir
    env_file:
      - .env
    ports:
        - 4799:80
    image: '${REGISTRY_NAME}strm/helloworld-http:latest'
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    networks:
      - "reverseproxy"
      - "internal"
networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal:
