version: "3.4"
services:
  http_server:
    env_file:
      - .env
    image: '${REGISTRY_NAME}strm/helloworld-http'
    expose: 
      - "80"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    networks:
      - "reverseproxy"
  
networks:
  reverseproxy:
    external:
      name: "reverseproxy"
