version: "3.4"
services:
  busy:
    env_file:
      - .env
    build:
      context: .
      dockerfile: busyDockerfile
    image: '${REGISTRY_NAME}busybox:latest'
  alp:
    env_file:
      - .env
    image: '${REGISTRY_NAME}alpine:latest'
