
version: "3.4"
services:
  http_server:
    ports:
      - 9438:9438
    env_file:
      - .env
    expose:
      - "9438"
    image: '${REGISTRY_NAME}henkel/bittorrent-tracker:latest'
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    networks:
      - "reverseproxy"
      - "internal"
networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal:
